language: python
services: redis-server
python:
 - "2.7"
 - "3.4"
 - "3.5"
install:
 - pip install --upgrade pip
 - pip install -r requirements.txt
 - pip install -r tests/requirements.txt
script:
 - flake8
 - nosetests tests
