language: python
services: redis-server
python:
 - "2.7"
 - "3.4"
 - "3.5"
install:
 - pip install --upgrade pip
 - pip install -r requirements.txt
 - pip install -r tests/requirements.txt
 - npm install
script:
 - flake8
 - npm run lint
 - localcrawl --start http://localhost:5000 --run-delay 10.0 --run databench --log DEBUG
 - html5validator --root _crawled/
 - nosetests tests
