language: python
services: redis-server
python:
 - "2.7"
install:
 - "pip install -r requirements.txt"
 - "pip install -r requirements_tests.txt"
before_script:
 - "databench &"
 - "sleep 30s"
script: "nosetests tests"
